"""Initial migration.

Revision ID: 39fdee6f182f
Revises: 
Create Date: 2021-11-17 21:57:26.775933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fdee6f182f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('origin_coord', sa.String(), nullable=True),
    sa.Column('destination_coord', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('datasource', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
