version: "3.7"
services:
 
  gra:
    image: grafana/grafana
    ports:
        - "3000:3000"
  db:
    image: mysql
     
    ports: 
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    ports:
        - 8080:8080
